mmb:
  name: MMBTask
  dataloader:
    batch_size: 8
    num_workers: 8
  dataset:
    name: MMBDataset
    split: dev
    root: ./data/MMBench
  gen_kwargs:
    max_length: 128
    top_k: 5
    num_beams: 1
    do_sample: False
    use_cache: True
