mme:
  name: MMETask
  dataloader:
    batch_size: 32
    num_workers: 8
  dataset:
    name: MMEDataset
    root: ./data/MME
  gen_kwargs:
    max_length: 20
    top_k: 5
    num_beams: 1
    do_sample: False
    use_cache: True
