seed:
  name: SEEDTask
  dataloader:
    batch_size: 32
    num_workers: 8
  dataset:
    name: SEEDDataset
    root: ./data/SEED-Bench
    target: image
  gen_kwargs:
    max_length: 20
    top_k: 5
    num_beams: 1
    do_sample: False
    use_cache: True
